// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 20 Nov 2021 18:13:09 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <inttypes.h>
#include <complex.h>
#include "host/libhackrf/src/hackrf.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// hackrf_sample_block_cb_fn_9f964168 is a proxy for callback hackrf_sample_block_cb_fn.
// int hackrf_sample_block_cb_fn_9f964168(hackrf_transfer* transfer);

