// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 20 Nov 2021 18:13:09 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

// int hackrf_sample_block_cb_fn_9f964168(hackrf_transfer* transfer) {
// 	return sampleBlockCbFn9F964168(transfer);
// }

