// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 20 Nov 2021 18:13:09 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package hackrf provides Go bindings for libhackrf
*/
package hackrf
