// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 20 Nov 2021 18:13:09 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package hackrf

/*
#cgo CFLAGS: -msse4.1 -Wall -fPIC -I. -I.. -I../host/libhackrf/src
#cgo LDFLAGS: -lm -lusb-1.0 ${SRCDIR}/../host/build/libhackrf/src/libhackrf.a
#include <inttypes.h>
#include <complex.h>
#include "host/libhackrf/src/hackrf.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
// import "C"
// import "unsafe"

// // ReadPartidSerialno as declared in src/hackrf.h:145
// type ReadPartidSerialno struct {
// 	PartId         [2]uint32
// 	SerialNo       [4]uint32
// 	ref58f14812    *C.read_partid_serialno_t
// 	allocs58f14812 interface{}
// }

// // OperacakeDwellTime as declared in src/hackrf.h:150
// type OperacakeDwellTime struct {
// 	Dwell          uint32
// 	Port           byte
// 	refc2030ff1    *C.hackrf_operacake_dwell_time
// 	allocsc2030ff1 interface{}
// }

// // OperacakeFreqRange as declared in src/hackrf.h:156
// type OperacakeFreqRange struct {
// 	FreqMin        uint16
// 	FreqMax        uint16
// 	Port           byte
// 	refa9b0a099    *C.hackrf_operacake_freq_range
// 	allocsa9b0a099 interface{}
// }
